import {AudioEngine} from './audio.js';import {VoiceSensor,MotionSensor,PulseSensor,hzToNote,NOTES} from './sensors.js';import {PerformanceState,STATE_NAMES,inferKey} from './state.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const audio=new AudioEngine(),voice=new VoiceSensor(),motion=new MotionSensor(),pulse=new PulseSensor($('#video'),$('#ppgCanvas')),state=new PerformanceState();let mode=['play','conduct','bio'].includes(new URLSearchParams(location.search).get('mode'))?new URLSearchParams(location.search).get('mode'):'play',running=false,lastKey={root:0,mode:'major',q:0};
$$('#modes button').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));$('#modeRead').textContent=mode==='play'?'PLAY ALONG':mode==='conduct'?'CONDUCTOR':'BIO';audio.mode=mode;const stateBox=$('#state');STATE_NAMES.forEach((n,i)=>{const d=document.createElement('div');d.className='state';d.innerHTML=`<span>${String(i+1).padStart(2,'0')} · ${n}</span><b id="s${i}">0.00</b>`;stateBox.appendChild(d)});
function msg(t,bad=false){const m=$('#message');m.textContent=t;m.style.color=bad?'#ff91a8':'#93a4c5'}
$$('#modes button').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('#modes button').forEach(x=>x.classList.toggle('active',x===b));$('#modeRead').textContent=mode==='play'?'PLAY ALONG':mode==='conduct'?'CONDUCTOR':'BIO';audio.mode=mode;msg(mode==='bio'?'Bio mode: tap heartbeat or enable camera PPG, then sing/move.':'Mode changed. Keep singing and moving.');});
$('#audio').onclick=async()=>{try{await audio.enable();audio.setVolume($('#volume').value);msg('Audio engine ready. Enable voice and motion next.')}catch(e){msg(e.message,true)}};
$('#mic').onclick=async()=>{try{await audio.enable();await voice.enable(audio.ctx);msg('Microphone analysis active. Your voice is analyzed but not routed back to the speaker.')}catch(e){msg('Microphone: '+e.message,true)}};
$('#motion').onclick=async()=>{try{await motion.enable();msg('Motion active. Tilt and rotate the phone to shape the band.')}catch(e){msg('Motion: '+e.message,true)}};
$('#camera').onclick=async()=>{try{await pulse.camera();msg('Camera PPG active. Cover the rear camera gently with a fingertip; reading is expressive/non-medical.')}catch(e){msg('Camera: '+e.message,true)}};
$('#tap').onclick=()=>{pulse.tap();msg('Heartbeat tap captured. Tap several beats for BPM/stability.')};
$('#perform').onclick=async()=>{await audio.enable();running=!running;$('#perform').textContent=running?'Stop Band':'Play With Me';running?audio.start():audio.stop();msg(running?'Band is listening and adapting locally.':'Band stopped; sensors can stay active.')};
$('#volume').oninput=e=>audio.setVolume(e.target.value);
addEventListener('cosmos-heart',e=>{const bpm=+e.detail?.bpm;if(bpm>30&&bpm<220){pulse.bpm=bpm;pulse.stability=Math.max(0,Math.min(1,+e.detail?.quality||1));msg(`Native heart source: ${e.detail?.source||'bridge'} · ${bpm.toFixed(0)} BPM`)}});
const c=$('#viz'),g=c.getContext('2d');function draw(vals){g.clearRect(0,0,c.width,c.height);g.strokeStyle='#253455';g.lineWidth=1;for(let y=30;y<c.height;y+=30){g.beginPath();g.moveTo(0,y);g.lineTo(c.width,y);g.stroke()}g.lineWidth=3;g.strokeStyle='#70f6d4';g.beginPath();vals.forEach((v,i)=>{const x=i/(vals.length-1)*c.width,y=c.height/2-v*(c.height*.38);i?g.lineTo(x,y):g.moveTo(x,y)});g.stroke();g.fillStyle='#9b8cff';for(let i=0;i<vals.length;i++){const x=i/(vals.length-1)*c.width,y=c.height/2-vals[i]*(c.height*.38);g.beginPath();g.arc(x,y,5,0,Math.PI*2);g.fill()}}
function tempoCoherence(){if(!pulse.bpm)return voice.energy>.08?.45:.2;return pulse.stability}
function harmonicTension(note,key){if(!note)return 0;const scale=key.mode==='minor'?[0,2,3,5,7,8,10]:[0,2,4,5,7,9,11];return scale.includes((note.pc-key.root+12)%12)?.15:.8}
function frame(){voice.update();pulse.update();if(voice.pcs.length>=5&&performance.now()%1500<20)lastKey=inferKey(voice.pcs);const n=hzToNote(voice.freq);const bpm=pulse.bpm||72;const x={voiceEnergy:voice.energy,pitchLock:voice.q,phraseFlux:voice.flux,tempoCoherence:tempoCoherence(),motionEnergy:motion.energy,tiltX:motion.tx,tiltY:motion.ty,rotationFlux:motion.rot,bpm,pulseStability:pulse.stability,harmonicTension:harmonicTension(n,lastKey),root:lastKey.root,mode:lastKey.mode,complexity:+$('#complexity').value};const vals=state.update(x);audio.update({...x,motionEnergy:x.motionEnergy*+$('#motionDepth').value,pulseStability:x.pulseStability*+$('#bioDepth').value});$('#note').textContent=n?.name||'—';$('#key').textContent=NOTES[lastKey.root]+' '+lastKey.mode;$('#bpm').textContent=(pulse.bpm||72).toFixed(0);vals.forEach((v,i)=>$('#s'+i).textContent=v.toFixed(2));draw(vals);requestAnimationFrame(frame)}
frame();
