export class AudioEngine {
  constructor(){this.ctx=null;this.master=null;this.comp=null;this.playing=false;this.timer=null;this.step=0;this.bpm=72;this.mode='play';this.root=0;this.minor=false;this.energy=.4;this.motion=.1;this.bio=.5;this.complexity=.55;}
  async enable(){if(!this.ctx){this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.comp=this.ctx.createDynamicsCompressor();this.comp.threshold.value=-18;this.comp.ratio.value=5;this.master.gain.value=.45;this.master.connect(this.comp).connect(this.ctx.destination);}await this.ctx.resume();}
  setVolume(v){if(this.master&&this.ctx)this.master.gain.setTargetAtTime(+v,this.ctx.currentTime,.03)}
  midi(n){return 440*Math.pow(2,(n-69)/12)}
  env(g,t,a=.01,d=.18,peak=.2){g.gain.cancelScheduledValues(t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.001,peak),t+a);g.gain.exponentialRampToValueAtTime(.0001,t+a+d)}
  tone(midi,t,d=.2,type='sine',gain=.12,detune=0){const o=this.ctx.createOscillator(),g=this.ctx.createGain(),f=this.ctx.createBiquadFilter();o.type=type;o.frequency.value=this.midi(midi);o.detune.value=detune;f.type='lowpass';f.frequency.value=900+this.motion*2400+this.energy*900;f.Q.value=1.2+this.bio*2;o.connect(f).connect(g).connect(this.master);this.env(g,t,.008,d,gain);o.start(t);o.stop(t+d+.08)}
  kick(t){const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.frequency.setValueAtTime(120,t);o.frequency.exponentialRampToValueAtTime(45,t+.12);o.connect(g).connect(this.master);this.env(g,t,.004,.16,.2);o.start(t);o.stop(t+.2)}
  hat(t){const b=this.ctx.createBuffer(1,900,this.ctx.sampleRate),a=b.getChannelData(0);for(let i=0;i<a.length;i++)a[i]=Math.random()*2-1;const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=b;f.type='highpass';f.frequency.value=5500;s.connect(f).connect(g).connect(this.master);this.env(g,t,.002,.045,.055);s.start(t);s.stop(t+.07)}
  chord(t,degree=0){const major=[[0,4,7],[5,9,12],[7,11,14],[9,12,16]],minor=[[0,3,7],[5,8,12],[7,10,14],[8,12,15]],tbl=this.minor?minor:major,pcs=tbl[degree%4],base=48+this.root;pcs.forEach((x,i)=>this.tone(base+x,t,.55+this.bio*.35,i?'sine':'triangle',.04+.035*this.energy,i*2));}
  tick(){if(!this.playing||!this.ctx)return;const beat=60/Math.max(40,Math.min(180,this.bpm)),t=this.ctx.currentTime+.035,s=this.step++;if(s%4===0)this.kick(t);if(s%2===1&&this.mode!=='bio')this.hat(t);if(s%4===0)this.chord(t,Math.floor(s/4)%4);if(this.mode!=='bio'||s%2===0)this.tone(36+this.root+[0,0,5,7][Math.floor(s/4)%4],t,.18,'square',.035+.04*this.energy);if(this.mode==='conduct'&&this.complexity>.35){const scale=this.minor?[0,2,3,5,7,8,10]:[0,2,4,5,7,9,11];const n=60+this.root+scale[(s+Math.floor(this.motion*6))%scale.length];this.tone(n,t+.04,.11+.1*this.bio,'sine',.025+.025*this.complexity)}if(this.mode==='bio'&&s%4===0){this.tone(72+this.root,t,.08,'sine',.08+this.bio*.05);this.tone(79+this.root,t+.08,.12,'sine',.04)}if(this.timer)clearTimeout(this.timer);this.timer=setTimeout(()=>this.tick(),beat*250)}
  start(){if(!this.ctx)return;this.playing=true;this.step=0;this.tick()}
  stop(){this.playing=false;clearTimeout(this.timer)}
  update(x){this.bpm=x.bpm||72;this.root=x.root||0;this.minor=x.mode==='minor';this.energy=x.voiceEnergy||0;this.motion=x.motionEnergy||0;this.bio=x.pulseStability||0;this.complexity=x.complexity??.55;}
}
