export const NOTES=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
export function hzToNote(hz){if(!hz)return null;const m=69+12*Math.log2(hz/440),n=Math.round(m);return {midi:n,pc:(n%12+12)%12,name:NOTES[(n%12+12)%12]+(Math.floor(n/12)-1),confidence:Math.max(0,1-Math.abs(m-n))}}
function autocorr(buf,sr){let mean=0;for(const v of buf)mean+=v;mean/=buf.length;let energy=0;const x=new Float32Array(buf.length);for(let i=0;i<x.length;i++){x[i]=buf[i]-mean;energy+=x[i]*x[i]}if(energy<.00001)return {hz:0,q:0};const lo=Math.floor(sr/1000),hi=Math.min(Math.floor(sr/70),x.length/2);let best=-1,bestLag=0;for(let lag=lo;lag<=hi;lag++){let num=0,a=0,b=0;for(let i=0;i<x.length-lag;i++){num+=x[i]*x[i+lag];a+=x[i]*x[i];b+=x[i+lag]*x[i+lag]}const c=num/Math.sqrt(a*b||1);if(c>best){best=c;bestLag=lag}}return best>.28?{hz:sr/bestLag,q:Math.min(1,Math.max(0,best))}:{hz:0,q:Math.max(0,best)}}
export class VoiceSensor{
 constructor(){this.ctx=null;this.an=null;this.stream=null;this.data=null;this.freq=0;this.q=0;this.energy=0;this.prevEnergy=0;this.flux=0;this.pcs=[]}
 async enable(audioCtx){this.ctx=audioCtx;this.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:false,autoGainControl:false},video:false});const src=this.ctx.createMediaStreamSource(this.stream);this.an=this.ctx.createAnalyser();this.an.fftSize=2048;this.an.smoothingTimeConstant=.25;src.connect(this.an);this.data=new Float32Array(this.an.fftSize)}
 update(){if(!this.an)return this;this.an.getFloatTimeDomainData(this.data);let e=0;for(const v of this.data)e+=v*v;this.energy=Math.min(1,Math.sqrt(e/this.data.length)*7);this.flux=Math.min(1,Math.abs(this.energy-this.prevEnergy)*8);this.prevEnergy=this.energy;const p=autocorr(this.data,this.ctx.sampleRate);this.freq=p.hz;this.q=p.q;if(this.freq&&this.q>.35){const n=hzToNote(this.freq);this.pcs.push({pc:n.pc,w:this.q*Math.max(.1,this.energy)});if(this.pcs.length>50)this.pcs.shift()}return this}
}
export class MotionSensor{
 constructor(){this.energy=0;this.tx=0;this.ty=0;this.rot=0;this.on=false}
 async enable(){if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function'){const r=await DeviceMotionEvent.requestPermission();if(r!=='granted')throw Error('Motion permission not granted')}addEventListener('devicemotion',e=>{const a=e.accelerationIncludingGravity||{},r=e.rotationRate||{},mag=Math.sqrt((a.x||0)**2+(a.y||0)**2+(a.z||0)**2);this.energy=.82*this.energy+.18*Math.min(1,Math.abs(mag-9.81)/5);const rm=Math.sqrt((r.alpha||0)**2+(r.beta||0)**2+(r.gamma||0)**2);this.rot=.85*this.rot+.15*Math.min(1,rm/180)});addEventListener('deviceorientation',e=>{this.tx=Math.max(-1,Math.min(1,(e.gamma||0)/45));this.ty=Math.max(-1,Math.min(1,(e.beta||0)/90))});this.on=true}
}
export class PulseSensor{
 constructor(video,canvas){this.video=video;this.canvas=canvas;this.ctx=canvas.getContext('2d',{willReadFrequently:true});this.stream=null;this.samples=[];this.peaks=[];this.bpm=0;this.stability=0;this.level=0;this.lastSample=0}
 tap(t=performance.now()/1000){if(this.peaks.length&&t-this.peaks.at(-1)<.25)return;this.peaks.push(t);if(this.peaks.length>12)this.peaks.shift();this._calc()}
 async camera(){this.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:320},height:{ideal:240}},audio:false});this.video.srcObject=this.stream;this.video.hidden=false;await this.video.play()}
 _calc(){const ints=[];for(let i=1;i<this.peaks.length;i++){const d=this.peaks[i]-this.peaks[i-1];if(d>=.3&&d<=1.5)ints.push(d)}if(!ints.length)return;const sorted=[...ints].sort((a,b)=>a-b),med=sorted[Math.floor(sorted.length/2)];this.bpm=60/med;if(ints.length>1){const mean=ints.reduce((a,b)=>a+b,0)/ints.length,sd=Math.sqrt(ints.reduce((a,b)=>a+(b-mean)**2,0)/ints.length);this.stability=Math.max(0,Math.min(1,1-sd/(mean||1)))}}
 update(now=performance.now()/1000){if(!this.stream||this.video.readyState<2||now-this.lastSample<.04)return this;this.lastSample=now;this.ctx.drawImage(this.video,0,0,this.canvas.width,this.canvas.height);const d=this.ctx.getImageData(0,0,this.canvas.width,this.canvas.height).data;let r=0,g=0;for(let i=0;i<d.length;i+=4){r+=d[i];g+=d[i+1]}const n=d.length/4,v=(r-g*.35)/n;this.samples.push({t:now,v});while(this.samples.length&&now-this.samples[0].t>8)this.samples.shift();if(this.samples.length>8){const recent=this.samples.slice(-20),mean=recent.reduce((a,s)=>a+s.v,0)/recent.length,prev=this.samples.at(-2)?.v??v;const threshold=mean+1.5;this.level=.9*this.level+.1*Math.min(1,Math.max(0,(v-mean)/12));if(v>threshold&&prev<=threshold&&(this.peaks.length===0||now-this.peaks.at(-1)>.35))this.tap(now)}return this}
}
